project_id = "rvcfnsufwuxncichgmhg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://lvlbhrsoohuupuyuzgka.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_confirmations = false

[functions.create-jira-ticket]
verify_jwt = false

[functions.create-customer-portal]

[functions.get-billing-info]

[functions.send-user-credentials]

[functions.delete-user]

[functions.cleanup-orphaned-users]

[functions.admin-user-management]

[functions.forgot-password]

[functions.reset-password]