// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gemknbowzgrtwlssputu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlbWtuYm93emdydHdsc3NwdXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjcwNzAsImV4cCI6MjA2NTY0MzA3MH0.LdMfHxmyfDisSQhtrkw1wAHQXUt3xaoXLAn7nRF-uCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);